<?php

// ENV FILE for UVOD-PORTAL
define('ENVIRONMENT', ENV['UVOD_ENVIRONMENT']);
define('UVOD_CONFIG', ENV['UVOD_CONFIG']);
define('UVOD_API_USER', ENV['UVOD_API_USER']);
define('UVOD_API_PASSWORD', ENV['UVOD_API_PASSWORD']);
define('UVOD_API_ENDPOINT', ENV['UVOD_API_ENDPOINT']);
define('UVOD_THEME', ENV['UVOD_THEME']);

?>