branch-defaults:
  dev:
    environment: clix-www-prd
environment-defaults:
  clix-www-prd:
    branch: null
    repository: null
global:
  application_name: UVOD-Portal
  default_ec2_keyname: univ-virginia
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/PHP 5.5 running on
    64bit Amazon Linux/2.1.7
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
